


SimOut = pvbiomass_plant_simulation(  SimParam, ...
                                      PvParam, ...
                                      BattParam,...
                                      InvParam, ...
                                      SimData,...
                                      BiomParam);