function [ pvKw, battKwh ] = get_most_expensive_solution(load, EcoPar, BattPar, InvPar,...
                            operationMatinenanceReplacementCost, investmentCost)
%GET_MOST EXPENSIVE SOLUTION Summary of this function goes here
%   Detailed explanation goes here
                                        
[nBattEmployed, yearsBattOperational] = get_worst_case_batt_use(load,...
                                        BattPar.minStateOfCharge,...
                                        EcoPar.plantLifetime );

loadPeakKw = max(load);
%inverter is designed on the peak power value
inverterCostTot = (loadPeakKw/InvPar.efficiency)...
                * EcoPar.inverterCostKw;

yearsBattRemaining = yearsBattOperational ...
               - mod(EcoPar.plantLifetime,  yearsBattOperational);


interestFactorLastYear = 1/(1+EcoPar.interestRate)^EcoPar.plantLifetime;
interestFactorHalfTime = 1/(1+EcoPar.interestRate)^(EcoPar.plantLifetime/2);
interestFactorEachYear = 0;
interestFactorReplacementYears = 0;

for t = 1:EcoPar.plantLifetime
    
    interestFactorEachYear = interestFactorEachYear...
                           + 1/(1+EcoPar.interestRate)^t;
                       
    if mod(t, yearsBattOperational) == 0
        interestFactorReplacementYears = interestFactorReplacementYears...
                                      + 1/(1+EcoPar.interestRate)^t;
    end
    
end


battKwh = (operationMatinenanceReplacementCost ...
        + (EcoPar.operationMaintenanceCostKw / EcoPar.pvCostKw) ...
        * interestFactorEachYear ...
        * (inverterCostTot - investmentCost/(1+ EcoPar.installBalanceOfSystemCost)) ...
        - inverterCostTot * interestFactorHalfTime) ...
        / (EcoPar.battCostKwh*(interestFactorReplacementYears ...
        - yearsBattRemaining*interestFactorLastYear ...
        - EcoPar.operationMaintenanceCostKw / EcoPar.pvCostKw ...
        * interestFactorEachYear));
    
pvKw = investmentCost/(EcoPar.pvCostKw*(1+EcoPar.installBalanceOfSystemCost)) ...
     - (EcoPar.battCostKwh*battKwh + inverterCostTot)/EcoPar.pvCostKw;
     
 
end

