function programatically

lFigWidth = 500; lFigHeight = 860;
f = figure('Visible','off','Units','pixels',...
           'Position',[340,80,lFigWidth,lFigHeight],'menubar','none');


% DEFAULT values 
% Simulation Parameters:
pvStartKw = '100';
pvStopKw = '200';
pvStepKw = '10';
battStartKwh = '1200';
battStopKwh = '1300';
battStepKwh = '10';
llpAccept = '5';
llpStart = '1';
llpStop = '80';
llpStep = '5';
  
% Economic Parameters
budget = '1500000';
pvCostKw = '1000';
battCostKwh = '140';              
battCostFixed = '0';             
inverterCostKw = '500';          
operationMaintenanceCostKw = '50';
installBalanceOfSystemCost = '2';%
plantLifetime = '20';           
interestRate = '6';%  

balanceOfSystem = '85';               
nominalAmbientTemperatureC = '20';    % Nominal ambient test-temperature of the panels [C]
nominalCellTemperatureC = '47';        % Nominal Operating Cell Temperature [C]
nominalIrradiation = '0.8';           % Irradiation at nominal operation [kW / m^2]
powerDerateDueTemperature = '0.004';  % Derating of panel's power due to temperature [/C]


% Margin metric
lMargin = 10;

% Title
lTitleHeight = 30;
lTitleWidth = 300;
lTitleStartY = lFigHeight - lMargin- lTitleHeight;
hTitle = uicontrol(f,'Style','text','String','Parameter Input',...
                   'Units','pixels','HorizontalAlignment','Left',...
                   'FontSize',16,...
                   'Position', [lMargin, lTitleStartY,...
                    lTitleWidth, lTitleHeight]);

% Panel Metrics
lNextRow = 50;

lTextWidth = 80;
lTextHeight = 40;

% SimPar Panel Metrics
lPanelKant = 70;
lnSimPar = 8;
lPanelWidth = lFigWidth*0.35;
lSimParPanelHeight = lNextRow*(lnSimPar)+lPanelKant;
lPanelsStartY = lTitleStartY - lMargin- lSimParPanelHeight;

hSimParamPanel = uipanel(f,'Title','Sim Parameters',...
                'Units','pixels',...
                'Position',[lMargin,lPanelsStartY ,lPanelWidth,lSimParPanelHeight]);

lTextY = lSimParPanelHeight-lPanelKant;
lTextX = lMargin;

lEditX = 0.6*lPanelWidth;
lEditY = lTextY+23;
lEditWidth = 0.3*lPanelWidth;
lEditHeight = 18;

% PV
uicontrol(hSimParamPanel,'Style','text','String','PV start [kW]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');
hPvStart = uicontrol(hSimParamPanel,'Style','edit','String',pvStartKw,...
                    'Units','pixels',...
                    'Position',[lEditX,lEditY,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
                
uicontrol(hSimParamPanel,'Style','text','String','PV stop [kW]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY - lNextRow,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');
hPvStop = uicontrol(hSimParamPanel,'Style','edit','String',pvStopKw,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY - lNextRow,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
                               
uicontrol(hSimParamPanel,'Style','text','String','PV step [kW]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY - lNextRow*2,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');
hPvStep = uicontrol(hSimParamPanel,'Style','edit','String',pvStepKw,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY - lNextRow*2,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');  

% Batt
uicontrol(hSimParamPanel,'Style','text','String','Batt start [kWh]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY - lNextRow*3,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');
hBattStart = uicontrol(hSimParamPanel,'Style','edit','String',battStartKwh,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY - lNextRow*3,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');  

                
uicontrol(hSimParamPanel,'Style','text','String','Batt stop [kWh]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY - lNextRow*4,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');
hBattStop = uicontrol(hSimParamPanel,'Style','edit','String',battStopKwh,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY - lNextRow*4,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');

uicontrol(hSimParamPanel,'Style','text','String','Batt step [kWh]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY - lNextRow*5,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');
hBattStep = uicontrol(hSimParamPanel,'Style','edit','String',battStepKwh,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY - lNextRow*5,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');

% LLP
uicontrol(hSimParamPanel,'Style','text','String','Llp Acceptance [%]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY - lNextRow*6,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');
hLlpAccept = uicontrol(hSimParamPanel,'Style','edit','String',llpAccept,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY - lNextRow*6,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');

uicontrol(hSimParamPanel,'Style','text','String','LLP start [%]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY - lNextRow*7,...
                     lTextWidth,lTextHeight],...
                     'HorizontalAlignment', 'Left');
hLlpStart = uicontrol(hSimParamPanel,'Style','edit','String',llpStart,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY - lNextRow*7,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
           
uicontrol(hSimParamPanel,'Style','text','String','LLP stop [%]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY - lNextRow*8,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');
hLlpStop = uicontrol(hSimParamPanel,'Style','edit','String',llpStop,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY - lNextRow*8,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');

uicontrol(hSimParamPanel,'Style','text','String','LLP step [%]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY - lNextRow*9,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');
hLlpStep = uicontrol(hSimParamPanel,'Style','edit','String',llpStep,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY - lNextRow*9,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');



% % Economic Parameters
lnEcoPar = 8;
lEcoParPanelHeight = lNextRow*(lnEcoPar)+lPanelKant;
lPanelsStartY = lTitleStartY - lMargin- lEcoParPanelHeight;
hBattParamPanel = uipanel(f,'Title','Economic Parameters',...
                  'Units','pixels',...
                  'Position',[lMargin + lPanelWidth,...
                  lPanelsStartY,lPanelWidth, lEcoParPanelHeight]);
              
lTextY = lEcoParPanelHeight-lPanelKant;
lEditY = lTextY + 22;

uicontrol(hBattParamPanel,'Style','text','String','Budget',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');               
hBudget= uicontrol(hBattParamPanel,'Style','edit','String',budget,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
                

uicontrol(hBattParamPanel,'Style','text','String','PV cost [/kW]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY-lNextRow,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');               
hPvCost= uicontrol(hBattParamPanel,'Style','edit','String',pvCostKw,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY-lNextRow,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
                

uicontrol(hBattParamPanel,'Style','text','String','Batt cost [/kWh]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY-lNextRow*2,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');               
hBattCost= uicontrol(hBattParamPanel,'Style','edit','String',battCostKwh,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY-lNextRow*2,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
                

uicontrol(hBattParamPanel,'Style','text','String','Batt cost fixed',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY-lNextRow*3,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');               
hBattCostFix= uicontrol(hBattParamPanel,'Style','edit','String',battCostFixed,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY-lNextRow*3,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
                

uicontrol(hBattParamPanel,'Style','text','String','Inverter Cost [\kW]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY-lNextRow*4,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');               
hInverterCost= uicontrol(hBattParamPanel,'Style','edit',...
                    'String',inverterCostKw,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY-lNextRow*4,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
                

uicontrol(hBattParamPanel,'Style','text','String','Operation and Maintenance cost [/kW]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY-lNextRow*5,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');               
hOperationMaintenanceCost= uicontrol(hBattParamPanel,'Style','edit',...
                    'String',operationMaintenanceCostKw,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY-lNextRow*5,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
                

uicontrol(hBattParamPanel,'Style','text','String','Installation and Balance of System [%]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY-lNextRow*6,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');               
hInstallBalanceOfSystemCost= uicontrol(hBattParamPanel,'Style','edit',...
                    'String',installBalanceOfSystemCost,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY-lNextRow*6,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
                
                
uicontrol(hBattParamPanel,'Style','text','String','Plant Lifetime [years]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY-lNextRow*7,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');               
hPlantLifetime = uicontrol(hBattParamPanel,'Style','edit',...
                    'String',plantLifetime,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY-lNextRow*7,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
                
uicontrol(hBattParamPanel,'Style','text','String','Interest rate [%]',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY-lNextRow*8,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');               
hInterestRate = uicontrol(hBattParamPanel,'Style','edit','String',interestRate,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY-lNextRow*8,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
                
% % PV Parameters
lnPvPar = 5;
lPvParPanelHeight = lNextRow*(lnPvPar)+lPanelKant;
lPanelsStartY = lPanelsStartY - lPvParPanelHeight;
hBattParamPanel = uipanel(f,'Title','Economic Parameters',...
                  'Units','pixels',...
                  'Position',[lMargin + lPanelWidth,...
                  lPanelsStartY,lPanelWidth, lPvParPanelHeight]);
              
lTextY = lPvParPanelHeight-lPanelKant;
lEditY = lTextY + 22;

uicontrol(hBattParamPanel,'Style','text','String','Budget',...
                    'Units','pixels',...
                    'Position',[lTextX,lTextY,...
                     lTextWidth,lTextHeight],...
                    'HorizontalAlignment', 'Left');               
hBudget= uicontrol(hBattParamPanel,'Style','edit','String',budget,...
                    'Units','pixels',...
                    'Position',[lEditX, lEditY,...
                     lEditWidth,lEditHeight],...
                    'HorizontalAlignment','Center');
                


            
% hInvParamPanel = uipanel(f,'Title','Battery Parameters',...
%                 'Position',[0.31,0.05,0.25,0.9],'Units','pixels');
%             
% hPVParamPanel = uipanel(f,'Title','Battery Parameters',...
%                 'Position',[0.31,0.05,0.25,0.9],'Units','pixels');
% 
% hEcoParamPanel = uipanel(f,'Title','Battery Parameters',...
%                 'Position',[0.31,0.05,0.25,0.9],'Units','pixels');
%             
%             
            
 



            
f.Visible = 'on';

end

